name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Add your build step here, e.g., npm install + build
      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      # Example: deploy to GitHub Pages (or replace with custom deployment)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
